language: go
go:
 - 1.12.x
services:
 - mysql
notifications:
 email: false
before_script: 				
 - export GO111MODULE=on
 - export ETHBLOCKS_DB=mysql
 - export ETHBLOCKS_DBHOST=localhost
 - export ETHBLOCKS_DBPORT=3306
 - export ETHBLOCKS_DBUSER_TEST=travis
 - export ETHBLOCKS_DBPASS_TEST=
 - export ETHBLOCKS_DBNAME_TEST=ethblocks_test
 - export ETHBLOCKS_DBPASSROOT=
script:
 - make
 - make test
