language: go
go:
 - 1.12.x
services:
 - mysql
notifications:
 email: false
before_script:
 - export GO111MODULE=on
 - echo "USE mysql;\nSET PASSWORD FOR 'travis'@'localhost' = PASSWORD('p');\nFLUSH PRIVILEGES;\n" | mysql -u root				
 - echo "USE mysql;\nSET PASSWORD FOR 'root'@'localhost' = PASSWORD('p');\nFLUSH PRIVILEGES;\n" | mysql -u root 				
 - export ETHBLOCKS_DB=mysql
 - export ETHBLOCKS_DBHOST=localhost
 - export ETHBLOCKS_DBPORT=3306
 - export ETHBLOCKS_DBUSER_TEST=travis
 - export ETHBLOCKS_DBPASS_TEST=p
 - export ETHBLOCKS_DBNAME_TEST=ethblocks_test
 - export ETHBLOCKS_DBPASSROOT=p
 - export ETHBLOCKS_DBSQL_MYSQL_TEST=$TRAVIS_BUILD_DIR/fixtures/ethblocks_mysql_test.sql
 - export ETHBLOCKS_DBSQL_MYSQL_SCHEMA=$TRAVIS_BUILD_DIR/sql/mysql/ethblocks_mysql_schema.sql
 - export ETHBLOCKS_DBSQL_MYSQL_TRUNCATE=$TRAVIS_BUILD_DIR/fixtures/ethblocks_mysql_truncate.sql
script:
 - make
 - make test
